AWSTemplateFormatVersion: '2010-09-09'
Description: Root stack that launches a web server using nested EC2 stack

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to SSH

Resources:
  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/my-cloudformationtemplate-bucket7/ec2.yml
      Parameters:
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName